feat: add _onStart precondition for script execution
BehaviorTree/BehaviorTree.CPP pull request #899
Opened 2024-12-17 03:55 UTC by Aglargil

Add a new precondition type _onStart that allows executing scripts before a node starts its tick. This provides symmetry with the existing _post functionality.

Resolves #895

2025-01-10 11:10 UTC, facontidavide requested changes

2025-01-10 11:10 UTC, facontidavide commented on include/behaviortree_cpp/tree_node.h
> +  ALWAYS,
```suggestion
  ON_START,
```

2025-01-10 11:10 UTC, facontidavide commented on src/tree_node.cpp
> +      if(preID == PreCond::ALWAYS)
```suggestion
      if(preID == PreCond::ON_START)
```

2025-01-10 11:10 UTC, facontidavide commented on src/tree_node.cpp
> +    case PreCond::ALWAYS:
```suggestion
    case PreCond::ON_START:
```

2025-01-10 15:03 UTC, Aglargil reviewed
ok

2025-01-23 01:53 UTC, Aglargil commented
Hi @facontidavide, I hope this message finds you well. I wanted to kindly follow up on the PR I submitted, which you reviewed previously. I understand you're likely very busy, but I was wondering if there might be any updates or further actions required from my side to move it forward. Thank you for your time and assistance.

2025-02-05 06:53 UTC, Aglargil commented
@facontidavide 
I hope you're doing well. I wanted to follow up on the PR I submitted a while ago. Just checking if there are any updates or additional actions needed from my side. Appreciate your help!

2025-02-06 06:21 UTC, closed without merging

2025-02-18 13:38 UTC, facontidavide commented
FYI, I have been working on this, but it will take time before it is merged.

2025-02-18 15:31 UTC, Aglargil commented
> FYI, I have been working on this, but it will take time before it is merged.仅供参考，我一直在做这项工作，但合并还需要时间。

@facontidavide I accidentally closed this PR, so I've reintroduced it(#932) and not only added _onStart, but also handled the CI error along the way. If the _onStart feature isn't merged so soon, do I need to raise a separate PR that handles CI errors?